#pragma once
// Memory and helpers for more bases than Koei's 42 cities / 87 bases (see bases.cpp, M7_LAYOUT.md).
#include <stdint.h>
#include <stddef.h>
#include "d3dtrace.h"

struct Bases {
    int C = 42, N = 87;
    // relocated arrays (patch-expression symbols of the same name)
    uint8_t *CITYARR = nullptr, *AIBASE = nullptr, *AICITY = nullptr, *AIUNIT = nullptr, *AIBLD16 = nullptr;
    uint8_t *AREAHEX = nullptr, *CITYBITS = nullptr, *AIRT = nullptr, *AREACOL = nullptr;
    uint8_t *UISCR_A = nullptr, *UISCR_B = nullptr, *UISCR_C = nullptr, *UISCR_D = nullptr, *UISCR_E = nullptr, *UISCR_F = nullptr;
    // tables that were static data (generated by tools/gen_bases.py into bases_tables.bin)
    uint8_t *AREAADJ = nullptr, *MAT87A = nullptr, *MAT87B = nullptr, *MATC = nullptr;
    uint8_t *AREA2CITY = nullptr, *AREA2BASE = nullptr, *CITYTAB844 = nullptr, *DBGBASE = nullptr;
    size_t sAREAADJ = 0, sMAT = 0, sMATC = 0, sAREA2CITY = 0, sAREA2BASE = 0, sCITYTAB844 = 0, sDBGBASE = 0;
    void* BLD_U8 = nullptr;      // get_building that maps the u8 "none" 0xff to NULL
    void* SER_U8ID = nullptr;    // i8 id field serializer reading ids 0..254 unsigned
    void* WPICK = nullptr;       // replacement of the weighted pick 0x5f7530 (int count, int result)
    void* SER_ID = nullptr;      // id field serializer: i16 (0x48a9e0) for streams marked 'WIDE', else SER_U8ID
    void* IDWIDE = nullptr;      // LONG: the stream being read / written has wide ids
};

// C = number of cities (42..1000). dir: data directory (bases_tables.bin)
bool basesSetup(int C, int U, const wchar_t* dir, Bases& b, TraceLogFn log);
