"""Build worldmod_terrain.txt / worldmod_terrain_caves.txt from mapmod_re/m4b_sites.jsonl (+ M3 lines).
Run by build_patches.py (cwd = the work directory)"""
import json
import os
import re
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
PROJ = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))).replace(os.sep, '/')
from detour import Builder  # noqa: E402

out_dir = sys.argv[1] if len(sys.argv) > 1 else 'm4b'
rows = [json.loads(l) for l in open(f'{PROJ}/m4b_sites.jsonl', encoding='utf-8') if l.strip()]

insn = {}
for l in open('out/pk.asm', encoding='utf-8'):
    p = l.rstrip('\n').split(None, 3)
    if len(p) >= 3:
        insn[int(p[0], 16)] = (bytes.fromhex(p[1]), p[2] + ' ' + (p[3] if len(p) > 3 else ''))

SKIP = {0x57ee0f, 0x57ee1b}          # opening camera: m3_patches.txt has the same change as f: expressions
lines, used = [], {}
for r in rows:
    if r['kind'] == 'cave':
        continue
    va = int(r['va'], 16)
    if va in SKIP:
        continue
    b, text = insn[va]
    size = int(r['size'])
    v = int(r['value'], 16) if not r['value'].startswith('-') else -int(r['value'][1:], 16)
    pat = struct.pack({4: '<I', 2: '<H', 1: '<B'}[size], v & ((1 << (8 * size)) - 1))
    offs = [m for m in range(1, len(b) - size + 1) if b[m:m + size] == pat]
    if len(offs) > 1 and 'off' in r:
        offs = [int(r['off'])]
    if len(offs) != 1:
        # prefer the field at the end of the instruction (immediate) or the displacement position
        raise SystemExit(f'{va:#x} {text}: value {r["value"]} found at {offs} in {b.hex()}')
    expr = r['expr'].replace(' ', '')
    key = (va, offs[0])
    if key in used:
        raise SystemExit(f'duplicate field {va:#x}+{offs[0]}')
    used[key] = expr
    lines.append(f'{va:08x} {offs[0]} {size} {b.hex()} {expr} ; [{r["kind"]}] {text.strip()} | {r.get("note", "")[:100]}')

m3 = open('m4b/m3_patches.txt', encoding='utf-8').read().splitlines()
lines += [l for l in m3 if l.strip()]

# caves
def bracify(t):
    t = re.sub(r'\((QB-S-8|QB-TG)\)/8', lambda m: '{(' + m.group(1) + ')/8}', t)
    t = re.sub(r'(?<!\{)\(([^(){}]*[A-Z][^(){}]*)\)(?!/8\})', lambda m: '{' + m.group(1) + '}', t)
    t = re.sub(r'(?<![{\w(+*/-])([A-Z][A-Z0-9_]*(?:[*+-](?:[A-Z][A-Z0-9_]*|0x[0-9a-f]+|\d+))*)(?![^{]*\})',
               lambda m: '{' + m.group(1) + '}', t)
    return t

patch_files = ['out/patches_m1.txt']
tmp = 'm4b/_terrain_inplace.txt'
open(tmp, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
patch_files.append(tmp)
bld = Builder(patch_files)
patched_vas = set(bld.patched)
for r in rows:
    if r['kind'] != 'cave':
        continue
    site = int(r['va'], 16)
    vas = [int(i.split(':')[0], 16) for i in r['insns']]
    steal = sum(len(insn[v][0]) for v in vas)
    assert vas[0] == site and steal == int(r['stolen_bytes']) and int(r['resume'], 16) == site + steal, r['va']
    clash = [hex(v) for v in vas if v in patched_vas]
    if clash:
        raise SystemExit(f'cave {r["va"]} steals patched instructions {clash}')
    text = bracify(r['replacement']).replace('\n', '; ')
    rep = {v: '' for v in vas}
    rep[site] = text
    bld.detour(site, rep, r.get('note', '')[:120], min_len=steal)
    print(f'{r["va"]}: {text}')
bld.write(f'{out_dir}/worldmod_terrain_caves.txt')
open(f'{out_dir}/worldmod_terrain.txt', 'w', encoding='utf-8').write(
    '; worldmod whole-world terrain (M4B.md) + China offset (M3). Generated by gen_terrain.py; do not edit.\n'
    + '\n'.join(lines) + '\n')
print(f'{len(lines)} in-place lines, {sum(1 for r in rows if r["kind"] == "cave")} caves -> {out_dir}')
